version: "2"

linters:
  default: none
  enable:
    - gocognit # 检查函数 Cognitive Complexity 复杂度


linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
run:
  tests: false
issues:
  exclude-dirs:
    - '(^|/)test($|/)'
